description: null
devices:
  adjust_period: 10
  capture:
    channels: 2
    device: hw:CARD=Loopback,DEV=0
    format: S24LE
    labels: null
    link_mute_control: null
    link_volume_control: null
    stop_on_inactive: null
    type: Alsa
  capture_samplerate: 192000
  chunksize: 4096
  enable_rate_adjust: true
  multithreaded: true
  playback:
    channels: 2
    device: hdmi:CARD=vc4hdmi,DEV=0
    format: S24LE
    type: Alsa
  queuelimit: 4
  rate_measure_interval: 1
  resampler: null
  samplerate: 192000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: false
  target_level: 8191
  volume_limit: null
  volume_ramp_time: null
  worker_threads: 2
filters:
  Bass:
    description: null
    parameters:
      freq: 90
      gain: 0
      q: 0.9
      type: Lowshelf
    type: Biquad
  Treble:
    description: null
    parameters:
      freq: 6500
      gain: 0
      q: 0.7
      type: Highshelf
    type: Biquad
mixers:
  2x2:
    channels:
      in: 2
      out: 2
    description: null
    labels: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -3
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: -3
        inverted: false
        mute: false
        scale: dB
pipeline:
- bypassed: false
  description: null
  name: 2x2
  type: Mixer
- bypassed: false
  channels: null
  description: null
  names:
  - Bass
  type: Filter
- bypassed: false
  channels: null
  description: null
  names:
  - Treble
  type: Filter
processors: {}
title: Loopback
